server:
  port: 8200
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        file-extension: yaml
        server-addr: localhost:8848
    #sentinel控制台
    sentinel:
      transport:
        dashboard: localhost:8888
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      enable: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/platform?allowMultiQueries=true&UseAffectedRows=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  #Redis配置
  redis:
    host: 47.105.204.66
    password: hhzh1234
    port: 6379
# flowable 配置
flowable:
  # 关闭异步，不关闭历史数据的插入就是异步的，会在同一个事物里面，无法回滚
  # 开发可开启会提高些效率，上线需要关闭
  async-executor-activate: false